<?php

namespace ContainerB2u1gfW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelDevContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FamilyController::newFamily' => ['privates', '.service_locator.C_lH.AB', 'get_ServiceLocator_CLH_ABService', true],
            'App\\Controller\\PersonController::deletePerson' => ['privates', '.service_locator.w3MCI1S', 'get_ServiceLocator_W3MCI1SService', true],
            'App\\Controller\\PersonController::listPerson' => ['privates', '.service_locator.JDImN0I', 'get_ServiceLocator_JDImN0IService', true],
            'App\\Controller\\PersonController::newPerson' => ['privates', '.service_locator.bZ30AFg', 'get_ServiceLocator_BZ30AFgService', true],
            'App\\Controller\\PersonController::updatePerson' => ['privates', '.service_locator.w3MCI1S', 'get_ServiceLocator_W3MCI1SService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\FamilyController:newFamily' => ['privates', '.service_locator.C_lH.AB', 'get_ServiceLocator_CLH_ABService', true],
            'App\\Controller\\PersonController:deletePerson' => ['privates', '.service_locator.w3MCI1S', 'get_ServiceLocator_W3MCI1SService', true],
            'App\\Controller\\PersonController:listPerson' => ['privates', '.service_locator.JDImN0I', 'get_ServiceLocator_JDImN0IService', true],
            'App\\Controller\\PersonController:newPerson' => ['privates', '.service_locator.bZ30AFg', 'get_ServiceLocator_BZ30AFgService', true],
            'App\\Controller\\PersonController:updatePerson' => ['privates', '.service_locator.w3MCI1S', 'get_ServiceLocator_W3MCI1SService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\FamilyController::newFamily' => '?',
            'App\\Controller\\PersonController::deletePerson' => '?',
            'App\\Controller\\PersonController::listPerson' => '?',
            'App\\Controller\\PersonController::newPerson' => '?',
            'App\\Controller\\PersonController::updatePerson' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\FamilyController:newFamily' => '?',
            'App\\Controller\\PersonController:deletePerson' => '?',
            'App\\Controller\\PersonController:listPerson' => '?',
            'App\\Controller\\PersonController:newPerson' => '?',
            'App\\Controller\\PersonController:updatePerson' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
