<?php

namespace ContainerQKM3jKQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CLH_ABService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C_lH.AB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C_lH.AB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'familyLogic' => ['privates', 'App\\Logic\\FamilyLogic', 'getFamilyLogicService', true],
        ], [
            'familyLogic' => 'App\\Logic\\FamilyLogic',
        ]);
    }
}
