<?php

namespace ContainerQKM3jKQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_637RuBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.63_7RuB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.63_7RuB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'aileRepository' => ['privates', 'App\\Repository\\AileRepository', 'getAileRepositoryService', true],
        ], [
            'aileRepository' => 'App\\Repository\\AileRepository',
        ]);
    }
}
