<?php

namespace ContainerQKM3jKQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W3MCI1SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w3MCI1S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w3MCI1S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'kisiRepository' => ['privates', 'App\\Repository\\KisiRepository', 'getKisiRepositoryService', true],
            'personLogic' => ['privates', 'App\\Logic\\PersonLogic', 'getPersonLogicService', true],
        ], [
            'kisiRepository' => 'App\\Repository\\KisiRepository',
            'personLogic' => 'App\\Logic\\PersonLogic',
        ]);
    }
}
