<?php

namespace Container9FsBw4n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BZ30AFgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bZ30AFg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bZ30AFg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'personLogic' => ['privates', 'App\\Logic\\PersonLogic', 'getPersonLogicService', true],
        ], [
            'personLogic' => 'App\\Logic\\PersonLogic',
        ]);
    }
}
