<?php

namespace Container9FsBw4n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zt9eDTcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zt9eDTc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zt9eDTc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'aileRepository' => ['privates', 'App\\Repository\\AileRepository', 'getAileRepositoryService', true],
            'familyLogic' => ['privates', 'App\\Logic\\FamilyLogic', 'getFamilyLogicService', true],
            'kisiRepository' => ['privates', 'App\\Repository\\KisiRepository', 'getKisiRepositoryService', true],
        ], [
            'aileRepository' => 'App\\Repository\\AileRepository',
            'familyLogic' => 'App\\Logic\\FamilyLogic',
            'kisiRepository' => 'App\\Repository\\KisiRepository',
        ]);
    }
}
