<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB2u1gfW\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB2u1gfW/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerB2u1gfW.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerB2u1gfW\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerB2u1gfW\App_KernelDevContainer([
    'container.build_hash' => 'B2u1gfW',
    'container.build_id' => 'd21e4550',
    'container.build_time' => 1594818501,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB2u1gfW');
