<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'new_family' => [[], ['_controller' => 'App\\Controller\\FamilyController::newFamily'], [], [['text', '/newFamily']], [], []],
    'update_family' => [['id'], ['_controller' => 'App\\Controller\\FamilyController::updateFamily'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/updateFamily']], [], []],
    'delete_family' => [['id'], ['_controller' => 'App\\Controller\\FamilyController::deleteFamily'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/deleteFamily']], [], []],
    'list_family' => [[], ['_controller' => 'App\\Controller\\FamilyController::listFamily'], [], [['text', '/listFamily']], [], []],
    'new_family_child' => [[], ['_controller' => 'App\\Controller\\FamilyController::newFamilyChild'], [], [['text', '/newFamilyChild']], [], []],
    'update_family_child' => [['id'], ['_controller' => 'App\\Controller\\FamilyController::updateFamilyChild'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/updateFamilyChild']], [], []],
    'delete_family_child' => [['id'], ['_controller' => 'App\\Controller\\FamilyController::deleteFamilyChild'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/deleteFamilyChild']], [], []],
    'list_family_child' => [[], ['_controller' => 'App\\Controller\\FamilyController::listFamilyChild'], [], [['text', '/listFamilyChild']], [], []],
    'home_index' => [[], ['_controller' => 'App\\Controller\\HomeController::familyShow'], [], [['text', '/']], [], []],
    'new_person' => [[], ['_controller' => 'App\\Controller\\PersonController::newPerson'], [], [['text', '/newPerson']], [], []],
    'update_person' => [['id'], ['_controller' => 'App\\Controller\\PersonController::updatePerson'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/updatePerson']], [], []],
    'delete_person' => [['id'], ['_controller' => 'App\\Controller\\PersonController::deletePerson'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/deletePerson']], [], []],
    'list_person' => [[], ['_controller' => 'App\\Controller\\PersonController::listPerson'], [], [['text', '/listPerson/']], [], []],
];
